#############################
#Color
#############################

export COLOR_BLACK="\033[0;30m"
export COLOR_BLUE="\033[0;34m"
export COLOR_BLUE_LIGHT="\033[1;34m"
export COLOR_CYAN="\033[0;36m"
export COLOR_CYAN_LIGHT="\033[1;36m"
export COLOR_GRAY_DARK="\033[1;30m"
export COLOR_GRAY_LIGHT="\033[0;37m"
export COLOR_GREEN="\033[0;32m"
export COLOR_GREEN_LIGHT="\033[1;32m"
export COLOR_ORANGE="\033[0;33m"
export COLOR_PURPLE="\033[0;35m"
export COLOR_PURPLE_LIGHT="\033[1;35m"
export COLOR_RED="\033[0;31m"
export COLOR_RED_LIGHT="\033[1;31m"
export COLOR_WHITE="\033[1;37m"
export COLOR_YELLOW="\033[1;33m"
export COLOR_END="\033[0m"

export COLOR_TEXT_BLINK="\e[5m" #\e[25m
export COLOR_TEXT_BOLD="\e[1m"
export COLOR_TEXT_BOLD_AND_ITALIC="\e[3m\e[1m"
export COLOR_TEXT_ITALIC="\e[3m"
export COLOR_TEXT_REVERSE="\e[7m" #\e[27m
export COLOR_TEXT_STRIKETHROUGH="\e[9m"
export COLOR_TEXT_UNDERLINE="\e[4m"
export COLOR_TEXT_YYY="\e[31m"
export COLOR_TEXT_ZZZ="\x1B[31m"
export COLOR_TEXT_END="\e[0m"

export COLOR_TEXT_BACKGROUND_WHITE_CYAN="\e[48:5:42m"
export COLOR_TEXT_BACKGROUND_WHITE_ORANGE="\e[48:2::240:143:104m"
export COLOR_TEXT_BACKGROUND_END="\e[49m"

#Color according to status
export COLOR_STATUS_DEFAULT="${COLOR_GRAY_DARK}"
export COLOR_STATUS_EMPTY="${COLOR_GRAY_DARK}"
export COLOR_STATUS_ERROR="${COLOR_RED_LIGHT}"
export COLOR_STATUS_SUCCESS="${COLOR_GREEN_LIGHT}"
export COLOR_STATUS_WARNING="${COLOR_ORANGE}"